This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file D:/Users/Matthias/Documents/07-Uni/03-Masterthesis/Masterthesis/Masterthesis_MatthiasWelter.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Masterthesis_MatthiasWelter.acn....done (103 entries accepted, 0 rejected).
Sorting entries....done (727 comparisons).
Generating output file Masterthesis_MatthiasWelter.acr....done (77 lines written, 0 warnings).
Output written in Masterthesis_MatthiasWelter.acr.
Transcript written in Masterthesis_MatthiasWelter.alg.
